#!/bin/bash

export
cd $OPENSHIFT_REPO_DIR

. ".openshift/config.stackdigest"

#create .protect_this_env on the server only. store credential details there. never check this into source control
source ${OPENSHIFT_DATA_DIR}/.protect_this_env

echo "MAIL_USERNAME = $MAIL_USERNAME"
echo "JAVA_OPTS = $JAVA_OPTS"
echo "VERTX_OPTS = $VERTX_OPTS"

# cd $EXAMPLE_DIR

echo "Starting Vert.x application!"

if [[ -e $SERVER_FILE ]]; then
	nohup bash -c "exec 'vertx' 'run' '${SERVER_FILE}' '-repo' 'vert-x.github.io' &> ${OPENSHIFT_DIY_LOG_DIR}vert.x.log" &> /dev/null &
	#echo $! > application.pid
else
	echo "Server file does not exists."
fi
